services:
  suitecrm-app-php:
    #image: suitecrm-app-php
    restart: unless-stopped
    platform: "linux/amd64"
    build:
      dockerfile: Dockerfile.Apache
      context: .
#      target: app_prod
    environment:
      TZ: ${TZ:-Asia/Baku}
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-prod}
    volumes:
      - app-data:/var/www/html
      - ./logs/app:/var/www/html/logs:rw
      - ./logs/apache:/var/www/log:rw
    depends_on:
      database:
        condition: service_healthy
    ports:
      # HTTP
      - target: 80
        published: 8080
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp
    tty: true

  database:
    image: mariadb
    ports: [ "3306" ]
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./mysql_init/:/docker-entrypoint-initdb.d:r
    environment:
      TZ: ${TZ:-Asia/Baku}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh" ,"--connect", "--innodb_initialized" ]
      timeout: 5s
      retries: 5
      start_period: 120s

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  mysql-data:
  app-data:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
